token: token-here
guildId: guild-id-here
channelId: channel-id-here
modChannelId: mod-channel-id-here
hour: 12
minute: 00
SendNoQuestionMessage: false
ReadoutPermission: ManageMessages
TimeModificationPermission: Administrator
RemovalPermission: Administrator
StopPermission: Administrator
AskQuestionPermission: Administrator
